<?php
/**
 * The Right Sidebar Template (Table of Contents & Secondary Widgets)
 *
 * @package CloudTech
 */

?>
<aside id="secondary-right" class="right-sidebar-col" aria-label="<?php esc_attr_e( 'Right Table of Contents Sidebar', 'cloudtech' ); ?>">
	<div class="right-sidebar-inner">
		
		<!-- Table of Contents Container -->
		<div id="toc-wrapper" class="toc-container">
			<h3 class="toc-header"><?php esc_html_e( 'ON THIS PAGE', 'cloudtech' ); ?></h3>
			<ul id="toc-list" class="toc-list">
				<!-- Dynamically generated by assets/js/toc.js -->
			</ul>
		</div>

		<?php
		if ( is_active_sidebar( 'right-sidebar' ) ) {
			echo '<div class="right-widgets-wrapper" style="margin-top: 36px; border-top: 1px dashed var(--color-grid-line); padding-top: 24px;">';
			dynamic_sidebar( 'right-sidebar' );
			echo '</div>';
		}
		?>

	</div>
</aside>
